### PR TITLE
Fix can't play movies on Android

### PR DESCRIPTION
**Pull request by krmbn0576**
Some changes for playing movies on RMMV.
- Fix can't play movies on Android (videoElement.play() is required on touchend)
- Make sure that wait until movie ended
- on iPhone/iPod, play movie inline
- Delete two global variables and a global function

### CODE REVIEW

**Comment by krmbn0576** [comment]
Oh no I suffer the same problem again!
How do I modify *index.html* and *GameFont.css*???

**Comment by ghost** [comment]
Oh, Original source layout have no directory for it.
Please make template/ dir.

**Comment by krmbn0576** [comment]
Hm, what should be included in the template folder?
I think It's enough to be set only *index.html* and *fonts/gamefont.css*.
*js/* are duplicated, and heavy binary files (ttf, png, m4a, ogg) shouldn't be set in this repository.
OK?

**Comment by ghost** [comment]
I agree.

**Comment by krmbn0576** [comment]
added template.

**Comment by ghost** [comment]
OK, LGTM

**Comment by krmbn0576** [comment]
I'll merge it soon although it's opened yesterday, because the same PR is opened once 8 days ago.

**Review by ghost — APPROVED** [review]

**Pull request merged**
