### PR TITLE
Add Auto Save System

### PR DESCRIPTION
**Pull request by krmbn0576**
Hey everyone, a long time no see!
We'll resume our activities.

This time we will provide an auto save system.
· Auto save to file 1 when "Transfer Player".
· For compatibility, this feature works only when "Auto Save" parameter is set to ON with Community_Basic. (Plugin style)

### CODE REVIEW

**Comment by krmbn0576** [comment]
I added feature system!
New features that include "Destructive" changes, are defined there.
Other plugins can know which features are enabled by `PluginManager.isFeatureEnabled(featureName)`.

**Comment by krmbn0576** [comment]
In RMMV 1.5.1, the new Plugin Manager was officially announced.
So, we adapt it, add `@type` to plugin patameters. 😇

**Comment by ghost** [comment]
LGTM.

but, you should separate PR next time.

**Comment by krmbn0576** [comment]
I'll be careful in future ;-)

**Comment by krmbn0576** [comment]
Hi @krmbn0576
This PR seems cool but I think your implementation of **Additional Feature System** is overkill.
So, I deleted them 😂

**Review by ghost — APPROVED** [review]
LGTM!

**Pull request merged**
