### PR TITLE
Game_Message#allText will throw error when Game_Message#_texts is empty array

### PR DESCRIPTION
**Pull request by wilfrem**
### about

`Array.prototype.reduce` will throw TypeError when array is empty and no initial value.
To resolve this probrem, just use `Array.prototype.join`.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Non-owner lgtm

**Comment by ghost** [comment]
LGTM but can you please make a new PR?
project structure is dramatically changed.

**Comment by wilfrem** [comment]
OK. I will do it today or tomorrow.

**Comment by hajimehoshi** [comment]
I think you don't need to close this issue.

**Comment by wilfrem** [comment]
new PR created. https://github.com/rpgtkoolmv/corescript/pull/28

**Comment by hajimehoshi** [comment]
You've created a new PR? Then close this PR. Sorry.

**Pull request closed without merging**
