### PR TITLE
Let's use WebGL on all devices!

### PR DESCRIPTION
**Pull request by krmbn0576**
See #30

### CODE REVIEW

**Comment by krmbn0576** [comment]
Well, I also disabled URL query parameter `?canvas` and `?webgl` to prevent misunderstanding that canvas mode is still being maintained.
Is it OK?

**Comment by ghost** [comment]
well, In the future, we can remove, but Canvas Mode is original implementation. 
And WebGL Mode may have bugs. (Ex. box calculation)

For debug purpose, We'd better not remove query parameters.

**Comment by krmbn0576** [comment]
OK, I restored them.

**Comment by ghost** [comment]
LGTM 🍣 
This PR will not be merged before memory-bloat .

**Review by ghost — APPROVED** [review]

**Pull request merged**
